name: Check URL

on:
  # push is just for testing
  push:
    branches:
      - main
  # schedule:
  #   - cron: '30 * * * *' # runs every hour on the 30 min mark

jobs:
  ping_url:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v4
        with:
          url: https://hairy-mushroom-soup.flyyyy.dev/
